# Generated by Django 4.1.2 on 2022-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('surface_app', models.CharField(max_length=250)),
                ('point_area', models.CharField(max_length=250)),
                ('delivery_date', models.CharField(max_length=250)),
                ('ral_code', models.CharField(max_length=250)),
                ('pipe_time', models.CharField(max_length=250)),
                ('node_time', models.CharField(max_length=250)),
                ('point_time', models.CharField(max_length=250)),
                ('pipe_dict', models.CharField(max_length=250)),
                ('node_dict', models.CharField(max_length=250)),
                ('pipe_point_dict', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
